baseURL: "https://example.com"
languageCode: "en-us"
title: "Hugo Novela"
pygmentsstyle: 'monokai'

params:
  social:
    twitter: "#"
    github: "#"
    instagram: "#"
    linkedin: "#"
    dribbble: "#"
    youtube: "#"
